### ISSUE TITLE
ModuleNotFoundError: No module named 'chromadb'

### ISSUE THREAD

**Issue by hjhjbmy** [DDizzzy79/Ret2GPT#1]
File /home/hjhjbmy/pwn.c already exists, thank god. 
 skipping "retdec-decompile", lets continue
[19:36:40] Created a chunk of size 1085, which is longer than the command_line.py:33
           specified 500                                                            
           Created a chunk of size 1047, which is longer than the command_line.py:33
           specified 500                                                            
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py", 
line 66, in __init__
    import chromadb
ModuleNotFoundError: No module named 'chromadb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ret2gpt", line 21, in <module>
    command_line.main()
  File "/home/hjhjbmy/Ret2GPT/built_in_command/command_line.py", line 125, in main
    loop()
  File "/home/hjhjbmy/Ret2GPT/built_in_command/command_line.py", line 109, in loop
    created_qa = pwnchain.create_qa(loader)
  File "/home/hjhjbmy/Ret2GPT/langchain_preprocess/prompt_builder.py", line 29, in 
create_qa
    db = Chroma.from_documents(split_files(loader), embeddings)
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py", 
line 338, in from_documents
    return cls.from_texts(
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py", 
line 301, in from_texts
    chroma_collection = cls(
  File "/usr/local/lib/python3.10/dist-packages/langchain/vectorstores/chroma.py", 
line 69, in __init__
    raise ValueError(
ValueError: Could not import chromadb python package. Please install it with `pip 
install chromadb`.

测试环境：
kali2021 / ubuntu2020 
python3.10
安装完所有的依赖后，运行报错。尝试过pip install chromadb --no-cache-dir 依旧没用
https://github.com/hwchase17/langchain/issues/1387
根据这个issue 也debug失败

**Comment by retr0reg** [comment]
收到 你可以先尝试 `python3 -m pip install chromadb` ? 如果还是错误的话 最好`pip`报错信息发给我 好来帮你

**Comment by hjhjbmy** [comment]
pip install chromadb --no-cache-dir
pip install tiktoken --no-cache-dir
安装完这两个依赖后 降低一下urllib3的版本 再配置一下终端的代理 就可以使用了

**Comment by 3186447858** [comment]
File "Ret2GPT.py", line 17, in <module>
    command_line.main()
  File "/home/ubuntu/Ret2GPT/built_in_command/command_line.py", line 134, in main
    loop()
  File "/home/ubuntu/Ret2GPT/built_in_command/command_line.py", line 107, in loop
    path = retdec.retdec()
  File "/home/ubuntu/Ret2GPT/decompile_file/main.py", line 8, in retdec
    raise Exception("Please provide a file to decompile, as `PwnGPT [your_file]`")
Exception: Please provide a file to decompile, as `PwnGPT [your_file]`
安装成功，运行报错，是unbuntu系统 python3.9版本

**Comment by 3186447858** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/ret2gpt", line 18, in <module>
    command_line.main()
  File "/home/ubuntu/Ret2GPT-main/built_in_command/command_line.py", line 134, in main
    loop()
  File "/home/ubuntu/Ret2GPT-main/built_in_command/command_line.py", line 107, in loop
    path = retdec.retdec()
  File "/home/ubuntu/Ret2GPT-main/decompile_file/main.py", line 16, in retdec
    subprocess.run(command)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'retdec-decompiler'
带上指定文件ret2gpt ./example2/hacknote ，报错如上。

**Comment by retr0reg** [comment]
你要安装retdec 建议根据你自己的平台去安装：https://github.com/avast/retdec

**Comment by 3186447858** [comment]
Exception: Please provide a file to decompile, as `PwnGPT [your_file]`

**Comment by 3186447858** [comment]
请大师给一个vm镜像或者virtrual box的的镜像百度云盘下载连接，我去下载这个吧

**Comment by 3186447858** [comment]
我有一openai的key，不用提供。

**Comment by retr0reg** [comment]
你提供了需要测试的二进制文件嘛 你要’ PwnGPT [你的文件路径]’ 才可以用

**Comment by 3186447858** [comment]
raceback (most recent call last):                                                                                        
  File "/root/.venv/lib/python3.11/site-packages/unstructured/nlp/tokenize.py", line 21, in 
_download_nltk_package_if_not_present
    nltk.find(f"{package_category}/{package_name}")
  File "/root/.venv/lib/python3.11/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt

  Searched in:
    - '/root/nltk_data'
    - '/root/.venv/nltk_data'
    - '/root/.venv/share/nltk_data'
    - '/root/.venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/Ret2GPT/Ret2GPT.py", line 21, in <module>
    command_line.main()
  File "/root/Ret2GPT/built_in_command/command_line.py", line 134, in main
    loop()
  File "/root/Ret2GPT/built_in_command/command_line.py", line 112, in loop
    created_qa = pwnchain.create_qa(loader)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/Ret2GPT/langchain_preprocess/prompt_builder.py", line 46, in create_qa
    db = Chroma.from_documents(split_files(loader), embeddings)
                               ^^^^^^^^^^^^^^^^^^^
  File "/root/Ret2GPT/langchain_preprocess/prompt_builder.py", line 36, in split_files
    document = loader.load()    
               ^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 86, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "/root/.venv/lib/python3.11/site-packages/langchain/document_loaders/unstructured.py", line 167, in _get_elements
    from unstructured.partition.auto import partition
  File "/root/.venv/lib/python3.11/site-packages/unstructured/partition/auto.py", line 16, in <module>
    from unstructured.partition.doc import partition_doc
  File "/root/.venv/lib/python3.11/site-packages/unstructured/partition/doc.py", line 8, in <module>
    from unstructured.partition.docx import partition_docx
  File "/root/.venv/lib/python3.11/site-packages/unstructured/partition/docx.py", line 33, in <module>
    from unstructured.partition.text_type import (
  File "/root/.venv/lib/python3.11/site-packages/unstructured/partition/text_type.py", line 21, in <module>
    from unstructured.nlp.tokenize import pos_tag, sent_tokenize, word_tokenize
  File "/root/.venv/lib/python3.11/site-packages/unstructured/nlp/tokenize.py", line 32, in <module>
    _download_nltk_package_if_not_present(package_name, package_category)
  File "/root/.venv/lib/python3.11/site-packages/unstructured/nlp/tokenize.py", line 23, in 
_download_nltk_package_if_not_present
    nltk.download(package_name)
  File "/root/.venv/lib/python3.11/site-packages/nltk/downloader.py", line 823, in download
    show(
  File "/root/.venv/lib/python3.11/site-packages/nltk/downloader.py", line 769, in show
    print_to(
  File "/root/.venv/lib/python3.11/site-packages/enrich/console.py", line 50, in print
    super().print(*args, **kwargs)
TypeError: Console.print() got an unexpected keyword argument 'file'

**Comment by 3186447858** [comment]
python3 Ret2GPT.py ./example2/hacknote      以上运行报错

**Comment by retr0reg** [comment]
开一个Python环境 执行import nltk和
nltk.download('punkt')下载哦 兄弟 提问题非常好，但是这种最好报错咱上网查一下 一般都能就解决😂

**Comment by 3186447858** [comment]
[08:29:17] Retrying (Retry(total=1, connect=None, read=None, redirect=None,              command_line.py:33
           status=None)) after connection broken by                                                        
           'NewConnectionError('<urllib3.connection.HTTPSConnection object at                              
           0x7fa252b3ae50>: Failed to establish a new connection: [Errno 101] Network is                   
           unreachable')': /v1/engines/text-embedding-ada-002/embeddings                                   
[08:31:28] Retrying (Retry(total=0, connect=None, read=None, redirect=None,              command_line.py:33
           status=None)) after connection broken by                                                        
           'NewConnectionError('<urllib3.connection.HTTPSConnection object at                              
           0x7fa252b3af90>: Failed to establish a new connection: [Errno 101] Network is                   
           unreachable')': /v1/engines/text-embedding-ada-002/embeddings                                   
[08:33:39] Retrying                                                                                                              command_line.py:33
           langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in                      
           10.0 seconds as it raised APIConnectionError: Error communicating with                          
           OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries                       
           exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by                     
           NewConnectionError('<urllib3.connection.HTTPSConnection object at                               
           0x7fa252b3b290>: Failed to establish a new connection: [Errno 101] Network is                   
           unreachable')).                     
解决了一大波问题。现在能跑起来了，现如下一直在跑程序，大师在帮我看看哪里不对。

**Comment by 3186447858** [comment]
> pip install chromadb --no-cache-dir pip install tiktoken --no-cache-dir 安装完这两个依赖后 降低一下urllib3的版本 再配置一下终端的代理 就可以使用了

请问大师怎么配置代理？

**Comment by 3186447858** [comment]
> 开一个Python环境 执行import nltk和 nltk.download('punkt')下载哦 兄弟 提问题非常好，但是这种最好报错咱上网查一下 一般都能就解决😂

请问openai代理如何设置
![255570586-5109352e-2a67-4ec9-8537-2c74b351c2b1](https://github.com/DDizzzy79/Ret2GPT/assets/139957734/2df4c1fd-8a6a-45c3-a8aa-33d538add077)
