### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'retdec-decompiler'

### ISSUE THREAD

**Issue by zhefox** [DDizzzy79/Ret2GPT#8]
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

                                                     Welcome to Ret2GPT
                                                      欢迎来到 Ret2GPT

                                         HINT: USE /help TO CHECK FOR COMMANDS
                                                 USE / TO USE COMMANDS

decompiling with retdec-decompile
Traceback (most recent call last):
  File "/usr/local/bin/Ret2GPT", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/Ret2GPT/main.py", line 4, in main
    command_line.main()
  File "/usr/local/lib/python3.10/dist-packages/Ret2GPT/Ret2GPT/command_line.py", line 124, in main
    loop()
  File "/usr/local/lib/python3.10/dist-packages/Ret2GPT/Ret2GPT/command_line.py", line 97, in loop
    path = retdec.retdec()
  File "/usr/local/lib/python3.10/dist-packages/Ret2GPT/Ret2GPT/decompile.py", line 16, in retdec
    subprocess.run(command)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'retdec-decompiler'

**Comment by retr0reg** [comment]
去下一个就ok（ubuntu 22.04以上的glibc才支持
